version: "3.7"

services:
  database:
    image: postgres
    container_name: desafio_queries_challenge_database
    restart: always
    ports:
      - 6543:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=queries_challenge
    volumes:
      - pgdata:/data/postgres

  app: 
    build: .
    container_name: desafio_queries_challenge_app
    ports: 
      - 3333:3333
      - 9229:9229 # Debug
    volumes:
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database
    environment:
      PORT: 6543
      DATABASE_URL: postgres://postgres:docker@db:5432/queries_challenge

volumes:
  pgdata:
    driver: local